### PR TITLE
Add remove-unit() function

### PR DESCRIPTION
**Pull request by kaishin**

### CODE REVIEW

**Comment by kaishin** [comment]
Ping @HugoGiraudel

**Comment by HugoGiraudel** [comment]
Looks all good, although I must say having to remove a unit with this function usually depicts a bad understanding / usage of units in Sass. Tl;dr: try to do otherwise.

**Comment by kaishin** [comment]
@HugoGiraudel That's a harsh generalization. I made this to avoid having to make a `rem()` function which is worse. One perfectly valid use case for this is making the pixel breakpoint corresponding to a non pixel value:
```scss
$container-width: 40rem;
$container-breakpoint: remove-unit(40rem) * 16px;
```

**Comment by HugoGiraudel** [comment]
This should be written as:

```scss
$container-width: 40rem;
$container-breakpoint: ($container-width / 1rem) * 16px;
```

**Comment by kaishin** [comment]
@HugoGiraudel That's not dry, is it?

**Comment by HugoGiraudel** [comment]
What?

**Comment by kaishin** [comment]
I mean if you end up doing that multiple times then it should be abstracted, at least partially.

**Comment by HugoGiraudel** [comment]
Yes. But certainly not as a `remove-unit` function.

```scss
@function pixify-breakpoint($value) {
  @if unitless($value) {
    @warn "Assuming $value to be in rem.";
    @return $value * 16px;
  } @else if unit($value) == 'rem' {
    @return $value / 1rem * 16px;
  }

  @return $value;
}
```

**Comment by kaishin** [comment]
@HugoGiraudel I don't get how that is any better. You said:

>  I must say having to remove a unit with this function usually depicts a bad understanding / usage of units in Sass.

But `$value / 1rem` does exactly that; it removes the unit from the value.

**Comment by kaishin** [comment]
The same functions can be written as:

```scss
@function pixify-breakpoint($value) {
  @if unitless($value) {
    @warn "Assuming $value to be in rem.";
    @return $value * 16px;
  } @else if unit($value) == 'rem' {
    @return remove-unit($value) * 16px;
  }

  @return $value;
}
```

**Comment by HugoGiraudel** [comment]
Give Chris Eppstein's opinions a read here: https://github.com/sass/sass/issues/533.

**Comment by kaishin** [comment]
Sorry @HugoGiraudel none of those arguments are convincing. Other people have already tackled this in other languages; see [Frink](http://futureboy.us/frinkdocs/#DataLibraries) for example. Making a `<Number>` unit-less is just another conversion from `some-unit` to `nil`, since a unit-less number is just a unit-ful number with a unit of `nil`. It is proper mathematical conversion.

All of the arguments in that issue are basically saying "we can't let this happen because it'll allow people to do improper math". The funny thing is Sass is full of things that allow people to do improper things. Example: passing a unit-less number to the `darken()` function, even though the docs clearly state it takes a percentage from 0% to 100%. Calling `darken(red, 4678)` is perfectly legal, even though it shouldn't be.

I can rewrite my original example as:

```scss
$container-rem-value: 40;
$container-width: $container-rem-value * 1rem;
$container-breakpoint: $container-rem-value * 16px;
```

or as:

```scss
$container-width: 40rem;
$container-breakpoint: remove-unit($container-width) * 16px;
```

These are exactly the same thing, mathematically speaking. The first converts a number with a unit of `nil` to `rem`, then converts the same number to `px`. The second bypasses defining the number with a unit of `nil` and calculates it inline where it is needed (only once in this case).

If we are going to rule out something, we'd better come up with better arguments than just "some people might misuse it". Anything can be misused, including basic operators (`200 / 0` oops what did I just do).

**Comment by HugoGiraudel** [comment]
I did not intend to start a flame war here Reda, my apologies. I was just giving my opinion about this function, which is, in my opinion, often misused. Your PR is very clean anyway, and can be merged.

**Comment by kaishin** [comment]
@HugoGiraudel It's nothing like that ;) I appreciate very much your input. I'm the number 1 proponent of not adding anything that is not vital, so I will close this for now.

**Comment by kaishin** [comment]
I ended up using this in the project I am working on (the name is tentative):

```scss
/// Takes a unit-less value and returns a map containing the equivalent `rem` and `px` values
/// @param {Number} $value
///   - The value that will be used for the `rem` key
/// @return {Map} The map containing the `rem` and `px` values

@function length($value) {
  @return (rem: $value * 1rem, px: $value * 16px);
}

$container-width: length(40);
$container-rem-width: map-get($container-width, rem);
$container-breakpoint: map-get($container-width, px);
```

**Comment by HugoGiraudel** [comment]
Aside from the name and the unquoted strings, I think it's nice.

**Pull request closed without merging**
